apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  type: clusterIP
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    nodePort: 32060
  selector:
    app: mysql
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: 
    ingress:
    - ip: clusterIP

