apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-master
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql-master
  template:
    metadata:
      labels:
        app: mysql-master
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQLDATA
          value: /var/lib/mysql
        image: mysql
        imagePullPolicy: Always
        name: mysql-master
        ports:
        - containerPort: 3306
          name: mysql-master
        volumeMounts:
        - name: mysqldata
          mountPath: /var/lib/mysql
      volumes:
      - name: mysqldata
        persistentVolumeClaim:
          claimName: mysqldb-persistent-volume-claim

