apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  clusterIP: 10.244.23.185
  clusterIPs:
  - 10.244.23.185
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    nodePort: 32060
  selector:
    app: mysql-master
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: 
    ingress:
    - ip: 192.168.7.127

