apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  type: clusterIP
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5432
    protocol: TCP
    nodePort: 32222
  selector:
    app: postgres
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: 
    ingress:
    - ip: clusterIP

